// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/interfaces.go -destination=internal/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	apimodel "backend_go/internal/model/apimodel"
	entitymodel "backend_go/internal/model/entitymodel"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *entitymodel.User) (*entitymodel.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*entitymodel.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// DeleteInactiveGuests mocks base method.
func (m *MockUserRepository) DeleteInactiveGuests(ctx context.Context, duration string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInactiveGuests", ctx, duration)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInactiveGuests indicates an expected call of DeleteInactiveGuests.
func (mr *MockUserRepositoryMockRecorder) DeleteInactiveGuests(ctx, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInactiveGuests", reflect.TypeOf((*MockUserRepository)(nil).DeleteInactiveGuests), ctx, duration)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*entitymodel.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*entitymodel.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*entitymodel.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entitymodel.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// SetOnSession mocks base method.
func (m *MockUserRepository) SetOnSession(ctx context.Context, id uuid.UUID, onSession bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOnSession", ctx, id, onSession)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOnSession indicates an expected call of SetOnSession.
func (mr *MockUserRepositoryMockRecorder) SetOnSession(ctx, id, onSession any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnSession", reflect.TypeOf((*MockUserRepository)(nil).SetOnSession), ctx, id, onSession)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// AutoRevealCardsInSession mocks base method.
func (m *MockSessionRepository) AutoRevealCardsInSession(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoRevealCardsInSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AutoRevealCardsInSession indicates an expected call of AutoRevealCardsInSession.
func (mr *MockSessionRepositoryMockRecorder) AutoRevealCardsInSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoRevealCardsInSession", reflect.TypeOf((*MockSessionRepository)(nil).AutoRevealCardsInSession), ctx, sessionID)
}

// ConnectUser mocks base method.
func (m *MockSessionRepository) ConnectUser(ctx context.Context, userID, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectUser", ctx, userID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectUser indicates an expected call of ConnectUser.
func (mr *MockSessionRepositoryMockRecorder) ConnectUser(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectUser", reflect.TypeOf((*MockSessionRepository)(nil).ConnectUser), ctx, userID, sessionID)
}

// CreateSession mocks base method.
func (m *MockSessionRepository) CreateSession(ctx context.Context, session *entitymodel.Session) (*entitymodel.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(*entitymodel.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionRepositoryMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionRepository)(nil).CreateSession), ctx, session)
}

// DeleteSession mocks base method.
func (m *MockSessionRepository) DeleteSession(ctx context.Context, sessionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionRepositoryMockRecorder) DeleteSession(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionRepository)(nil).DeleteSession), ctx, sessionId)
}

// DisconnectUser mocks base method.
func (m *MockSessionRepository) DisconnectUser(ctx context.Context, userID, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisconnectUser", ctx, userID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisconnectUser indicates an expected call of DisconnectUser.
func (mr *MockSessionRepositoryMockRecorder) DisconnectUser(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisconnectUser", reflect.TypeOf((*MockSessionRepository)(nil).DisconnectUser), ctx, userID, sessionID)
}

// GetByCreator mocks base method.
func (m *MockSessionRepository) GetByCreator(ctx context.Context, userId string) ([]entitymodel.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCreator", ctx, userId)
	ret0, _ := ret[0].([]entitymodel.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCreator indicates an expected call of GetByCreator.
func (mr *MockSessionRepositoryMockRecorder) GetByCreator(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCreator", reflect.TypeOf((*MockSessionRepository)(nil).GetByCreator), ctx, userId)
}

// GetByID mocks base method.
func (m *MockSessionRepository) GetByID(ctx context.Context, sessionId string) (*entitymodel.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, sessionId)
	ret0, _ := ret[0].(*entitymodel.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSessionRepositoryMockRecorder) GetByID(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSessionRepository)(nil).GetByID), ctx, sessionId)
}

// GetCountUsersInUserSessions mocks base method.
func (m *MockSessionRepository) GetCountUsersInUserSessions(ctx context.Context, userId string) (map[uuid.UUID]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountUsersInUserSessions", ctx, userId)
	ret0, _ := ret[0].(map[uuid.UUID]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountUsersInUserSessions indicates an expected call of GetCountUsersInUserSessions.
func (mr *MockSessionRepositoryMockRecorder) GetCountUsersInUserSessions(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountUsersInUserSessions", reflect.TypeOf((*MockSessionRepository)(nil).GetCountUsersInUserSessions), ctx, userId)
}

// GetUsers mocks base method.
func (m *MockSessionRepository) GetUsers(ctx context.Context, sessionID uuid.UUID) ([]apimodel.UsersInSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, sessionID)
	ret0, _ := ret[0].([]apimodel.UsersInSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockSessionRepositoryMockRecorder) GetUsers(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockSessionRepository)(nil).GetUsers), ctx, sessionID)
}

// RevealCardsInSession mocks base method.
func (m *MockSessionRepository) RevealCardsInSession(ctx context.Context, sessionID uuid.UUID, isReveal bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevealCardsInSession", ctx, sessionID, isReveal)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevealCardsInSession indicates an expected call of RevealCardsInSession.
func (mr *MockSessionRepositoryMockRecorder) RevealCardsInSession(ctx, sessionID, isReveal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevealCardsInSession", reflect.TypeOf((*MockSessionRepository)(nil).RevealCardsInSession), ctx, sessionID, isReveal)
}

// MockVoteRepository is a mock of VoteRepository interface.
type MockVoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVoteRepositoryMockRecorder
	isgomock struct{}
}

// MockVoteRepositoryMockRecorder is the mock recorder for MockVoteRepository.
type MockVoteRepositoryMockRecorder struct {
	mock *MockVoteRepository
}

// NewMockVoteRepository creates a new mock instance.
func NewMockVoteRepository(ctrl *gomock.Controller) *MockVoteRepository {
	mock := &MockVoteRepository{ctrl: ctrl}
	mock.recorder = &MockVoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoteRepository) EXPECT() *MockVoteRepositoryMockRecorder {
	return m.recorder
}

// DeleteVoteInSession mocks base method.
func (m *MockVoteRepository) DeleteVoteInSession(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVoteInSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVoteInSession indicates an expected call of DeleteVoteInSession.
func (mr *MockVoteRepositoryMockRecorder) DeleteVoteInSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVoteInSession", reflect.TypeOf((*MockVoteRepository)(nil).DeleteVoteInSession), ctx, sessionID)
}

// GetVotesInSessions mocks base method.
func (m *MockVoteRepository) GetVotesInSessions(ctx context.Context, sessionID uuid.UUID) ([]entitymodel.Vote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotesInSessions", ctx, sessionID)
	ret0, _ := ret[0].([]entitymodel.Vote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotesInSessions indicates an expected call of GetVotesInSessions.
func (mr *MockVoteRepositoryMockRecorder) GetVotesInSessions(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotesInSessions", reflect.TypeOf((*MockVoteRepository)(nil).GetVotesInSessions), ctx, sessionID)
}

// SetVoteValue mocks base method.
func (m *MockVoteRepository) SetVoteValue(ctx context.Context, sessionID, userID uuid.UUID, vote string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVoteValue", ctx, sessionID, userID, vote)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetVoteValue indicates an expected call of SetVoteValue.
func (mr *MockVoteRepositoryMockRecorder) SetVoteValue(ctx, sessionID, userID, vote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVoteValue", reflect.TypeOf((*MockVoteRepository)(nil).SetVoteValue), ctx, sessionID, userID, vote)
}
