// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Dmitriy Kazakov",
            "email": "kda94@mail.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/guest_login": {
            "post": {
                "description": "Создание временной гостевой учетной записи",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Позволяет войти как гость",
                "parameters": [
                    {
                        "description": "Данные гостя",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_apimodel.GuestLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная аутентификация гостя",
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_apimodel.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Аутентификация пользователя по email и паролю",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_apimodel.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная аутентификация",
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_apimodel.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учетные данные",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение информации об авторизованном пользователе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Получить текущего пользователя",
                "responses": {
                    "200": {
                        "description": "Данные пользователя",
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_apimodel.UserProfile"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Создание нового аккаунта пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_apimodel.UserRegister"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_apimodel.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Пользователь уже существует или ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение списка сессий, созданных текущим пользователем",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Получить мои сессии",
                "responses": {
                    "200": {
                        "description": "Список сессий пользователя",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/backend_go_internal_model_entitymodel.Session"
                            }
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Гостевой пользователь не имеет доступа",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создание новой сессии для планирования с возможностью голосования",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Создать сессию",
                "parameters": [
                    {
                        "description": "Данные для создания сессии",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_apimodel.SessionCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Сессия успешно создана",
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_apimodel.CreateSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{session_id}": {
            "get": {
                "description": "Получение информации о конкретной сессии по её идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Получить сессию по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID сессии",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные сессии",
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_entitymodel.Session"
                        }
                    },
                    "404": {
                        "description": "Сессия не найдена",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаление сессии по ID (только для создателя сессии)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Удалить сессию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID сессии",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сессия успешно удалена",
                        "schema": {
                            "$ref": "#/definitions/backend_go_internal_model_apimodel.DeleteSessionResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен (гостевой пользователь или не создатель сессии)",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Сессия не найдена",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "backend_go_internal_model.DeckType": {
            "type": "string",
            "enum": [
                "fibonacci",
                "modified_fibonacci",
                "tshirt",
                "hydra",
                "classic"
            ],
            "x-enum-varnames": [
                "DeckTypeFibonacci",
                "DeckTypeModifiedFibonacci",
                "DeckTypeTShirt",
                "DeckTypeHydra",
                "DeckTypeClassic"
            ]
        },
        "backend_go_internal_model_apimodel.CreateSessionResponse": {
            "description": "Данные созданной сессии",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "session_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                }
            }
        },
        "backend_go_internal_model_apimodel.DeleteSessionResponse": {
            "description": "Результат операции удаления сессии",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Сессия успешно удалена"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "backend_go_internal_model_apimodel.GuestLogin": {
            "description": "Данные для создания гостевого аккаунта",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Guest User"
                }
            }
        },
        "backend_go_internal_model_apimodel.SessionCreate": {
            "type": "object",
            "properties": {
                "deck_type": {
                    "$ref": "#/definitions/backend_go_internal_model.DeckType"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "backend_go_internal_model_apimodel.TokenResponse": {
            "description": "Токены доступа и обновления",
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "backend_go_internal_model_apimodel.UserLogin": {
            "description": "Данные для входа пользователя",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "securepassword123"
                }
            }
        },
        "backend_go_internal_model_apimodel.UserProfile": {
            "description": "Полная информация о пользователе",
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "is_guest": {
                    "type": "boolean",
                    "example": false
                },
                "is_verified": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "oauth_provider": {
                    "type": "string",
                    "example": "google"
                }
            }
        },
        "backend_go_internal_model_apimodel.UserRegister": {
            "description": "Данные для регистрации нового пользователя",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "example": "securepassword123"
                }
            }
        },
        "backend_go_internal_model_entitymodel.Session": {
            "type": "object",
            "properties": {
                "allow_emoji": {
                    "type": "boolean"
                },
                "auto_reveal": {
                    "type": "boolean"
                },
                "cards_revealed": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "created_via": {
                    "type": "string"
                },
                "creator_id": {
                    "type": "string"
                },
                "creator_name": {
                    "type": "string"
                },
                "deck_type": {
                    "$ref": "#/definitions/backend_go_internal_model.DeckType"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_api_handler.ErrorResponse": {
            "description": "Сообщение об ошибке",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid credentials"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT токен в формате: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Аутентификация и управление пользователями",
            "name": "auth"
        },
        {
            "description": "Управление сессиями планирования и голосования",
            "name": "sessions"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Backend Go API",
	Description:      "API для управления сессиями планирования с системой аутентификации и WebSocket",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
